### ISSUE TITLE
Ambiguous entry in MPDS

### ISSUE THREAD

**Issue by muhrin** [mpds-io/mpds-api#9] opened 2017-11-28 09:17 UTC
We're having a problem with entry S452097 (https://mpds.io/#entry/S452097).

The entry on the website says the composition is Mg2Pb but the entry from the database (both the JSON and CIF representations) have it as MgPb2.  Also in the ICSD the corresponding structure is listed as Mg2Pb.  Unfortunately we've don't have access to the original source so we can't confirm which is right.

**Comment by blokhin** [comment] 2017-11-28 13:51
Thanks, that's an internal artifact of the PAULING FILE. I will report it to the editors. Hopefully they will fix it in the 2018 version.

**Comment by muhrin** [comment] 2017-11-28 15:17
Thanks Evgeny. We find quite a number of problematic entries. Is there
somewhere we can signal such entries directly? Github are good for us but
if you have another mechanism we're happy to use it...

Le 28 nov. 2017 2:51 PM, "Evgeny Blokhin" <notifications@github.com> a
écrit :

**Comment by blokhin** [comment] 2017-11-28 17:39
Here is fine. The reason is that I need to make sure, the artifacts are not caused by the MPDS, but originate directly to the PAULING FILE.

**Comment by blokhin** [comment] 2018-02-02 20:31
Fixed in the Release 2018

**Closed as completed by blokhin** 2018-02-02 20:31 UTC
Labels: bug, PAULINGFILE
